### ISSUE TITLE
How to hide the overlay

### ISSUE THREAD

**Issue by stefanKBL** [anseki/plain-overlay#3]
Hi,
great library. Doing some test, il see that on hide method, SVG and div with class plainoverlay plainoverlay-hide stays on DOM. So when you open overlay (eg. on post form) and then hide overlay (eg. on post form error), then post again... DOM have multiple div class plainoverlay plainoverlay-hide.
Should it be possible to destroy vs hide ?
Thanks

**Comment by anseki** [comment]
Hi @skobeo, thank you for the comment.
So, do you mean that you want to remove the `<div>` element that was created by the PlainOverlay from the page?

**Comment by stefanKBL** [comment]
yes, destroy the div from DOM or perhaps reuse it only if _id is same; as i notice when a do a console.log from an instance (ie. namespace.overlay=PlainOverlay.show(target)), instance give me an _id which seems to be incremental.

**Comment by anseki** [comment]
Sorry, my English is poor...
Do you mean that the `<div>` element is not reused when the overlay is re-opened?
One instance of PlainOverlay  should have only one overlay (i.e. one `<div>` tree).
In other words, do you mean that multiple overlays are added when `show` method of an instance is called?

**Comment by anseki** [comment]
Oh, did you use a static method `PlainOverlay.show` to show a overlay?
i.e. did you not use the constructor `new PlainOverlay(...)`?

**Comment by stefanKBL** [comment]
my English too :- i'm french
situation is from a form with an ajax submit action
click submit : show method create a new DIV, thats ok.
ajax response then hide method do not destroy this div, but apply css hidden
re-click calling show method create another DIV

i use static method.

**Comment by anseki** [comment]
I see.
The static method `PlainOverlay.show` is a shorthand for `(new PlainOverlay(target, options)).show()
`.
See document: https://anseki.github.io/plain-overlay/#plainoverlayshow
That is, the static method you used creates new instance every time.

You should get an instance to use instance method such as `hide` method.
And, you can show/hide the overlay any number of times.
For example, try examples in this URL:
https://anseki.github.io/plain-overlay/
Click "SHOW" button and "HIDE" button many times.

```js
var overlay = new PlainOverlay();

// Show the overlay when the form was submitted.
myForm.addEventListener('submit' function() { overlay.show(); });

// Hide the overlay when the ajax failed.
myAjax.addEventListener('error' function() { overlay.hide(); });
```

See: https://anseki.github.io/plain-overlay/#methods

**Comment by stefanKBL** [comment]
ok thanks. it works. but should be nice to have a destroy method, as when navigate page to page without reloading Dom, could have necessity to open multiple instance. However this is another question. So this issue is closed. Thanks again.

**Comment by anseki** [comment]
Happy to help you. :smile: 
Yes, please close this issue, and make new issue about the destroy method.
