### ISSUE TITLE
support default hide start state

### ISSUE THREAD

**Issue by mesutyigit** [anseki/plain-overlay#4]
var overlay = new PlainOverlay(document.getElementById('userTable'),{
            face: document.getElementById('loadingSvg'),
            style: {backgroundColor: 'rgba(255, 255, 255, 0.6)'},
            blur: 0
        });

overlay is starting show mode always.  
I wanna define overlay instance and later show/hide method.

**Comment by anseki** [comment]
Hi @mesutyigit, thank you for the comment.

By default, an overlay is hidden. Could you show me the code that has the problem?

BTW, the `blur: 0` is not needed because default value is `false`.

**Comment by anseki** [comment]
No reply came, and I close this issue.
